import type { Metadata } from "next";
import "./globals.css";
import TaxAssistHeader from "./components/TaxAssistHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <TaxAssistHeader />
        {children}
      </body>
    </html>
  );
}
